export interface GraphNodeItem {
  id: string;
  label: string;
  sublabel: string;
  file: string;
  risk: 'changed' | 'high' | 'medium' | 'low';
  depth: number;
  x: number;
  y: number;
  callers: number;
  callees: number;
  upstream: string[];
  downstream: string[];
}

export interface AffectedSymbolItem {
  name: string;
  file: string;
  lines: string;
  risk: 'high' | 'medium' | 'low';
  reason: string;
  callers: number;
  depth: number;
}

export interface RepoSpecification {
  name: string;
  org: string;
  branch: string;
  commit: string;
  generatedAt: string;
  traversalDepth: number;
  targetSymbol: string;
  targetFile: string;
  changeType: string;
  summary: string;
  recommendation: string;
  diffContent: string;
  affectedSymbols: AffectedSymbolItem[];
  highImpact: Array<{ file: string; description: string }>;
  mediumImpact: Array<{ file: string; description: string }>;
  lowImpactCount: number;
  lowImpactDescription: string;
  nodes: GraphNodeItem[];
  edges: Array<{ from: string; to: string }>;
  defaultSelectedNode: string;
}

export const REPO_SPECIFICATIONS: Record<string, RepoSpecification> = {
  'api-gateway': {
    name: 'api-gateway',
    org: 'acme-corp',
    branch: 'main',
    commit: 'a3f2c9d',
    generatedAt: '2 min ago',
    traversalDepth: 3,
    targetSymbol: 'applyRateLimit()',
    targetFile: 'src/middleware/rateLimit.ts',
    changeType: 'Sliding Window Algorithm Update',
    summary: 'Changing applyRateLimit() affects 6 route modules, 14 files, and downstream Redis sliding window storage.',
    recommendation: 'Benchmark Redis cluster throughput under high concurrent traffic before adjusting sliding window intervals.',
    diffContent: `- router.use(rateLimit({ windowMs: 60000, max: 100 }));
+ router.use(slidingWindowRateLimit({
+   windowMs: 60000,
+   max: 150,
+   redisCluster: true,
+   keyGenerator: (req) => req.user?.id || req.ip
+ }));`,
    affectedSymbols: [
      {
        name: 'PaymentRouter.processRoutes',
        file: 'src/routes/payments.ts',
        lines: 'L18–L34',
        risk: 'high',
        reason: 'Directly relies on strict rate limit override (20 req/min)',
        callers: 4,
        depth: 1,
      },
      {
        name: 'AuthRouter.loginRoute',
        file: 'src/routes/auth.ts',
        lines: 'L12–L28',
        risk: 'high',
        reason: 'Directly relies on brute-force login rate limiting (10 req/min)',
        callers: 6,
        depth: 1,
      },
      {
        name: 'UserRouter.profileRoutes',
        file: 'src/routes/users.ts',
        lines: 'L45–L62',
        risk: 'high',
        reason: 'Inherits gateway sliding window rate limit policy',
        callers: 3,
        depth: 1,
      },
      {
        name: 'RedisService.slidingWindow',
        file: 'src/services/redis.ts',
        lines: 'L88–L110',
        risk: 'medium',
        reason: 'Stores sliding window keys and timestamp sorted sets in Redis',
        callers: 2,
        depth: 2,
      },
      {
        name: 'LoggingMiddleware.logRateLimit',
        file: 'src/middleware/logging.ts',
        lines: 'L30–L42',
        risk: 'medium',
        reason: 'Emits structured JSON audit logs on 429 Too Many Requests',
        callers: 1,
        depth: 2,
      },
      {
        name: 'Templates.rateLimitReceipt',
        file: 'src/templates/receipt.ts',
        lines: 'L14–L28',
        risk: 'low',
        reason: 'Formats rate limit metadata for API error headers',
        callers: 1,
        depth: 3,
      },
    ],
    highImpact: [
      { file: 'src/routes/payments.ts', description: 'Applies strict rate limit (20 req/min)' },
      { file: 'src/routes/auth.ts', description: 'Applies login brute-force rate limit (10 req/min)' },
      { file: 'src/routes/users.ts', description: 'Inherits default gateway limit' },
    ],
    mediumImpact: [
      { file: 'src/services/redis.ts', description: 'Sliding window key expiration and storage' },
      { file: 'src/middleware/logging.ts', description: 'Emits 429 Too Many Requests log events' },
    ],
    lowImpactCount: 9,
    lowImpactDescription: '+ 9 downstream route handlers, health checks, and route tests',
    defaultSelectedNode: 'rateLimit-middleware',
    nodes: [
      {
        id: 'api-gateway',
        label: 'api-gateway',
        sublabel: 'server.ts',
        file: 'src/server.ts',
        risk: 'high',
        depth: 0,
        x: 18,
        y: 28,
        callers: 14,
        callees: 2,
        upstream: ['clients'],
        downstream: ['rateLimit-middleware', 'logging-middleware'],
      },
      {
        id: 'logging-middleware',
        label: 'logging.ts',
        sublabel: 'logRequest()',
        file: 'src/middleware/logging.ts',
        risk: 'medium',
        depth: 0,
        x: 18,
        y: 72,
        callers: 14,
        callees: 1,
        upstream: ['api-gateway'],
        downstream: ['rateLimit-middleware'],
      },
      {
        id: 'rateLimit-middleware',
        label: 'rateLimit.ts',
        sublabel: 'applyRateLimit() [TARGET]',
        file: 'src/middleware/rateLimit.ts',
        risk: 'changed',
        depth: 1,
        x: 50,
        y: 45,
        callers: 6,
        callees: 4,
        upstream: ['api-gateway', 'logging-middleware'],
        downstream: ['payments-route', 'auth-route', 'users-route', 'redis-service'],
      },
      {
        id: 'payments-route',
        label: 'payments.ts',
        sublabel: 'POST /payments',
        file: 'src/routes/payments.ts',
        risk: 'high',
        depth: 2,
        x: 82,
        y: 20,
        callers: 2,
        callees: 1,
        upstream: ['rateLimit-middleware'],
        downstream: ['payment-service'],
      },
      {
        id: 'auth-route',
        label: 'auth.ts',
        sublabel: 'POST /auth/login',
        file: 'src/routes/auth.ts',
        risk: 'high',
        depth: 2,
        x: 82,
        y: 44,
        callers: 3,
        callees: 1,
        upstream: ['rateLimit-middleware'],
        downstream: ['user-auth'],
      },
      {
        id: 'users-route',
        label: 'users.ts',
        sublabel: 'GET /users/me',
        file: 'src/routes/users.ts',
        risk: 'high',
        depth: 2,
        x: 82,
        y: 68,
        callers: 1,
        callees: 0,
        upstream: ['rateLimit-middleware'],
        downstream: [],
      },
      {
        id: 'redis-service',
        label: 'redis.ts',
        sublabel: 'slidingWindow()',
        file: 'src/services/redis.ts',
        risk: 'medium',
        depth: 2,
        x: 82,
        y: 88,
        callers: 1,
        callees: 0,
        upstream: ['rateLimit-middleware'],
        downstream: [],
      },
    ],
    edges: [
      { from: 'api-gateway', to: 'rateLimit-middleware' },
      { from: 'api-gateway', to: 'logging-middleware' },
      { from: 'logging-middleware', to: 'rateLimit-middleware' },
      { from: 'rateLimit-middleware', to: 'payments-route' },
      { from: 'rateLimit-middleware', to: 'auth-route' },
      { from: 'rateLimit-middleware', to: 'users-route' },
      { from: 'rateLimit-middleware', to: 'redis-service' },
    ],
  },

  'payment-service': {
    name: 'payment-service',
    org: 'acme-corp',
    branch: 'main',
    commit: 'b12c3d4',
    generatedAt: '10 min ago',
    traversalDepth: 3,
    targetSymbol: 'processPayment()',
    targetFile: 'src/services/payment.service.ts',
    changeType: 'Idempotency Key & Surcharge Addition',
    summary: 'Changing processPayment() affects 5 services, 12 files, and downstream invoice generation.',
    recommendation: 'Add integration tests around checkout and payment gateway before making changes.',
    diffContent: `- async function processPayment(orderId: string, amount: number) {
-   return stripeClient.charges.create({ amount, currency: 'usd' });
- }
+ async function processPayment(
+   orderId: string,
+   amount: number,
+   idempotencyKey: string
+ ): Promise<PaymentResult> {
+   return stripeClient.charges.create({ amount, currency: 'usd' }, { idempotencyKey });
+ }`,
    affectedSymbols: [
      {
        name: 'CheckoutService.initiateCheckout',
        file: 'src/services/checkout.service.ts',
        lines: 'L112–L145',
        risk: 'high',
        reason: 'Calls processPayment() directly with checkout payload',
        callers: 3,
        depth: 1,
      },
      {
        name: 'OrderService.finalizeOrder',
        file: 'src/services/order.service.ts',
        lines: 'L78–L96',
        risk: 'high',
        reason: 'Depends on checkout completion flow and status verification',
        callers: 2,
        depth: 1,
      },
      {
        name: 'InvoiceGenerator.generateInvoice',
        file: 'src/services/invoice.service.ts',
        lines: 'L45–L70',
        risk: 'high',
        reason: 'Generates invoice, tax calculation, and payment receipt',
        callers: 2,
        depth: 1,
      },
      {
        name: 'NotificationService.sendConfirmation',
        file: 'src/services/notification.service.ts',
        lines: 'L22–L38',
        risk: 'medium',
        reason: 'Sends customer payment confirmation email & SMS',
        callers: 1,
        depth: 2,
      },
      {
        name: 'AnalyticsService.trackPaymentEvent',
        file: 'src/services/analytics.service.ts',
        lines: 'L15–L30',
        risk: 'medium',
        reason: 'Tracks revenue conversion and payment failure metrics',
        callers: 1,
        depth: 2,
      },
      {
        name: 'types/PaymentResult',
        file: 'src/types/payment.ts',
        lines: 'L10–L24',
        risk: 'low',
        reason: 'PaymentResult schema and transaction status definitions',
        callers: 5,
        depth: 0,
      },
    ],
    highImpact: [
      { file: 'src/services/checkout.service.ts', description: 'Calls processPayment() directly' },
      { file: 'src/services/order.service.ts', description: 'Depends on checkout completion flow' },
      { file: 'src/services/invoice.service.ts', description: 'Generates invoice and tax records after payment' },
    ],
    mediumImpact: [
      { file: 'src/services/notification.service.ts', description: 'Sends payment confirmation' },
      { file: 'src/services/analytics.service.ts', description: 'Tracks payment events' },
    ],
    lowImpactCount: 7,
    lowImpactDescription: '+ 7 receipt views, refund hooks, and webhook dispatchers',
    defaultSelectedNode: 'payment-service',
    nodes: [
      {
        id: 'checkout-service',
        label: 'checkout.service.ts',
        sublabel: 'initiateCheckout()',
        file: 'src/services/checkout.service.ts',
        risk: 'high',
        depth: 0,
        x: 18,
        y: 28,
        callers: 3,
        callees: 1,
        upstream: ['api-gateway'],
        downstream: ['payment-service'],
      },
      {
        id: 'auth-service',
        label: 'auth.service.ts',
        sublabel: 'verifySession()',
        file: 'src/services/auth.service.ts',
        risk: 'medium',
        depth: 0,
        x: 18,
        y: 72,
        callers: 8,
        callees: 1,
        upstream: ['api-gateway'],
        downstream: ['payment-service'],
      },
      {
        id: 'payment-service',
        label: 'payment.service.ts',
        sublabel: 'processPayment() [TARGET]',
        file: 'src/services/payment.service.ts',
        risk: 'changed',
        depth: 1,
        x: 50,
        y: 50,
        callers: 5,
        callees: 4,
        upstream: ['checkout-service', 'auth-service'],
        downstream: ['order-service', 'invoice-service', 'notification-service', 'analytics-service'],
      },
      {
        id: 'order-service',
        label: 'order.service.ts',
        sublabel: 'finalizeOrder()',
        file: 'src/services/order.service.ts',
        risk: 'high',
        depth: 2,
        x: 82,
        y: 20,
        callers: 2,
        callees: 1,
        upstream: ['payment-service'],
        downstream: ['invoice-service'],
      },
      {
        id: 'invoice-service',
        label: 'invoice.service.ts',
        sublabel: 'generateInvoice()',
        file: 'src/services/invoice.service.ts',
        risk: 'high',
        depth: 2,
        x: 82,
        y: 44,
        callers: 2,
        callees: 0,
        upstream: ['payment-service', 'order-service'],
        downstream: [],
      },
      {
        id: 'notification-service',
        label: 'notification.service.ts',
        sublabel: 'sendConfirmation()',
        file: 'src/services/notification.service.ts',
        risk: 'medium',
        depth: 2,
        x: 82,
        y: 68,
        callers: 1,
        callees: 0,
        upstream: ['payment-service'],
        downstream: [],
      },
      {
        id: 'analytics-service',
        label: 'analytics.service.ts',
        sublabel: 'trackPaymentEvent()',
        file: 'src/services/analytics.service.ts',
        risk: 'medium',
        depth: 2,
        x: 82,
        y: 88,
        callers: 1,
        callees: 0,
        upstream: ['payment-service'],
        downstream: [],
      },
    ],
    edges: [
      { from: 'checkout-service', to: 'payment-service' },
      { from: 'auth-service', to: 'payment-service' },
      { from: 'payment-service', to: 'order-service' },
      { from: 'payment-service', to: 'invoice-service' },
      { from: 'payment-service', to: 'notification-service' },
      { from: 'payment-service', to: 'analytics-service' },
      { from: 'order-service', to: 'invoice-service' },
    ],
  },

  'user-auth': {
    name: 'user-auth',
    org: 'acme-corp',
    branch: 'develop',
    commit: 'c91a3be',
    generatedAt: '1 hour ago',
    traversalDepth: 3,
    targetSymbol: 'verifyToken()',
    targetFile: 'src/middleware/authenticate.ts',
    changeType: 'JWT Algorithm Validation Update',
    summary: 'Changing verifyToken() affects 8 services, 19 files, and all session verification paths.',
    recommendation: 'Ensure backwards compatibility with existing active JWT tokens before deploying key rotation.',
    diffContent: `- export const verifyToken = (token: string) => jwt.verify(token, SECRET);
+ export const verifyToken = (
+   token: string,
+   options?: jwt.VerifyOptions
+ ): JwtPayload => {
+   return jwt.verify(token, SECRET, { algorithms: ['HS256', 'RS256'], ...options }) as JwtPayload;
+ };`,
    affectedSymbols: [
      {
        name: 'SessionsRouter.validateSession',
        file: 'src/routes/sessions.ts',
        lines: 'L15–L32',
        risk: 'high',
        reason: 'Validates active JWTs on every incoming request',
        callers: 8,
        depth: 1,
      },
      {
        name: 'RbacMiddleware.requireRole',
        file: 'src/middleware/rbac.ts',
        lines: 'L20–L44',
        risk: 'high',
        reason: 'Extracts user permissions and role hierarchy from token',
        callers: 5,
        depth: 1,
      },
      {
        name: 'TokenService.refreshToken',
        file: 'src/services/tokens.ts',
        lines: 'L50–L72',
        risk: 'high',
        reason: 'Handles token rotation and secret signature verification',
        callers: 3,
        depth: 1,
      },
      {
        name: 'OAuthService.handleCallback',
        file: 'src/services/oauth.ts',
        lines: 'L34–L58',
        risk: 'high',
        reason: 'Exchanges GitHub OAuth authorization codes for session JWTs',
        callers: 2,
        depth: 1,
      },
      {
        name: 'ProfileController.getMe',
        file: 'src/controllers/profile.ts',
        lines: 'L10–L25',
        risk: 'medium',
        reason: 'Reads authenticated user context and claims',
        callers: 2,
        depth: 2,
      },
      {
        name: 'AdminController.restrictElevated',
        file: 'src/controllers/admin.ts',
        lines: 'L28–L48',
        risk: 'medium',
        reason: 'Restricts superuser actions based on token claims',
        callers: 1,
        depth: 2,
      },
      {
        name: 'CryptoUtils.decryptToken',
        file: 'src/utils/crypto.ts',
        lines: 'L12–L30',
        risk: 'medium',
        reason: 'AES-256-GCM token encryption & decryption at rest',
        callers: 2,
        depth: 2,
      },
      {
        name: 'models/User',
        file: 'src/models/user.ts',
        lines: 'L5–L18',
        risk: 'low',
        reason: 'User profile schema and identity definitions',
        callers: 6,
        depth: 0,
      },
    ],
    highImpact: [
      { file: 'src/routes/sessions.ts', description: 'Validates active JWTs on each request' },
      { file: 'src/middleware/rbac.ts', description: 'Extracts user permissions and role hierarchy' },
      { file: 'src/services/tokens.ts', description: 'Handles token rotation and secret verification' },
      { file: 'src/services/oauth.ts', description: 'Exchanges GitHub OAuth codes for session JWTs' },
    ],
    mediumImpact: [
      { file: 'src/controllers/profile.ts', description: 'Reads authenticated user context' },
      { file: 'src/controllers/admin.ts', description: 'Restricts actions based on token claims' },
      { file: 'src/utils/crypto.ts', description: 'AES-256-GCM token encryption & decryption' },
    ],
    lowImpactCount: 12,
    lowImpactDescription: '+ 12 authenticated controllers, session stores, and security test suites',
    defaultSelectedNode: 'verifyToken',
    nodes: [
      {
        id: 'auth-middleware',
        label: 'authenticate.ts',
        sublabel: 'authHeader()',
        file: 'src/middleware/authenticate.ts',
        risk: 'high',
        depth: 0,
        x: 18,
        y: 35,
        callers: 19,
        callees: 1,
        upstream: ['http-requests'],
        downstream: ['verifyToken'],
      },
      {
        id: 'crypto-utils',
        label: 'crypto.ts',
        sublabel: 'decryptToken()',
        file: 'src/utils/crypto.ts',
        risk: 'medium',
        depth: 0,
        x: 18,
        y: 75,
        callers: 4,
        callees: 0,
        upstream: ['verifyToken'],
        downstream: [],
      },
      {
        id: 'verifyToken',
        label: 'verifyToken()',
        sublabel: 'jwt.verify() [TARGET]',
        file: 'src/middleware/authenticate.ts',
        risk: 'changed',
        depth: 1,
        x: 50,
        y: 50,
        callers: 8,
        callees: 5,
        upstream: ['auth-middleware'],
        downstream: ['sessions-route', 'rbac-middleware', 'token-service', 'oauth-service', 'crypto-utils'],
      },
      {
        id: 'sessions-route',
        label: 'sessions.ts',
        sublabel: 'GET /sessions/me',
        file: 'src/routes/sessions.ts',
        risk: 'high',
        depth: 2,
        x: 82,
        y: 18,
        callers: 3,
        callees: 0,
        upstream: ['verifyToken'],
        downstream: [],
      },
      {
        id: 'rbac-middleware',
        label: 'rbac.ts',
        sublabel: 'requireRole()',
        file: 'src/middleware/rbac.ts',
        risk: 'high',
        depth: 2,
        x: 82,
        y: 40,
        callers: 5,
        callees: 0,
        upstream: ['verifyToken'],
        downstream: [],
      },
      {
        id: 'token-service',
        label: 'tokens.ts',
        sublabel: 'refreshToken()',
        file: 'src/services/tokens.ts',
        risk: 'high',
        depth: 2,
        x: 82,
        y: 62,
        callers: 2,
        callees: 0,
        upstream: ['verifyToken'],
        downstream: [],
      },
      {
        id: 'oauth-service',
        label: 'oauth.ts',
        sublabel: 'handleCallback()',
        file: 'src/services/oauth.ts',
        risk: 'high',
        depth: 2,
        x: 82,
        y: 84,
        callers: 1,
        callees: 0,
        upstream: ['verifyToken'],
        downstream: [],
      },
    ],
    edges: [
      { from: 'auth-middleware', to: 'verifyToken' },
      { from: 'verifyToken', to: 'sessions-route' },
      { from: 'verifyToken', to: 'rbac-middleware' },
      { from: 'verifyToken', to: 'token-service' },
      { from: 'verifyToken', to: 'oauth-service' },
      { from: 'verifyToken', to: 'crypto-utils' },
    ],
  },
};

export function getRepoSpec(repoKeyOrName?: string): RepoSpecification {
  const clean = (repoKeyOrName || 'api-gateway').split('/').pop()?.trim().toLowerCase() || 'api-gateway';
  return REPO_SPECIFICATIONS[clean] || REPO_SPECIFICATIONS['api-gateway'];
}
